Getting Started
================================================================================

This section describes what the Online Linguistic Database does and how to get
and install it.

.. toctree::
   :maxdepth: 2

   about
   installation


Architecture
================================================================================

The architecture section provides details about the design of the OLD.

.. toctree::
   :maxdepth: 2

   architecture
   interface
   datastructure


API Documentation
================================================================================
 
This section contains the API documentation automatically extracted from the
source code.

.. toctree::
   :maxdepth: 4

   api


If you can't find the information you're looking for, have a look at the index
or try to find it using the search function:


* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
